### PR TITLE
Refactor updater

### LINKED ISSUE #280: Refactor Updater
- [x] Split into fetch repository and insert data to storage
- [x] All errors are handled in Updater #224
  - checksum mismatch (signature does not fit)
  - hash missmatch (file was manipulated)
  - fingerprint missmatch (signed with wrong key)
  - network error (file not found o.e.)
- [x] remove yearly option from update intervals
- [x] improve updater feedback (signed/times batch)

### PR DESCRIPTION
**Pull request by eppfel**
So, finally...

Generating more user feedback and therefore fiddling with Ember.js took me nearly as much time as rewriting the updater :joy:

@apoller I found two configuration options `secureUpdateEnabled`and `forceSecureUpdate`, but I cannot recall why we have both? Should `secureUpdateEnabled` be mutable by the user in the settings? And `forceSecureUpdate` overrides this? Right now both can only be set in the study-creator.

The UI looks like this now:

bildschirmfoto 2017-01-14 um 15 17 26

---

bildschirmfoto 2017-01-14 um 16 11 43

The labels might look too much like buttons... 

And is it correct, how I use the `signed` label:

not update, yet (so "signed", because it is the original config that was delivered to participant.
OR
secureUpdateEnabled
OR
forceSecureUpdate

…otherwise `unsigned `

fixes #280

### CODE REVIEW

**Comment by iamolivinius** [comment]
secureUpdateEnabled should verify signatures and warn if it is invalid

forceSecureUpdate should verify signatures and fail if it is invalid

**Comment by eppfel** [comment]
> secureUpdateEnabled should verify signatures and warn if it is invalid

If you update it anyway, why would you verify it at all?

I just saw, the second screenshot has the grey unlocked label saying "signed", this is already fixed.

**Comment by iamolivinius** [comment]
Debugging?! I can't think of any other reasons.

**Comment by eppfel** [comment]
@apoller Your opinion on this? Remove "enableSecureUpdate" or add the functionality as describe by @iamolivinius ?

**Comment by apoller** [comment]
It's like @iamolivinius commented 
secureUpdateEnabled means that it should notify if signature check fails but should proceed anywqay
forceSecureUpdate means that signature check must pass otherwise the update isn't done

**Comment by eppfel** [comment]
Ok, then I have to add one case to the updater. So, far I only differentiate two cases.

**Comment by eppfel** [comment]
> secureUpdateEnabled means that it should notify if signature check fails but should proceed anywqay

I just thought about it again and this still does not make sense to me. The info about failed verification would be seen by the participant. This will create confusion. As a researcher: Why not disable verification completely, if you update anyway?

Do I miss a certain use-case?

**Comment by apoller** [comment]
Actually we can reduce everything to the forceSecureUpdate function and can remove the other option

**Pull request merged**
